### ISSUE TITLE
Linear probing map without allocated entry objects

### ISSUE THREAD

**Issue by dzaima** [nomemory/open-addressing-java-maps#1]
A very important property of open addressing is the ability to not need an allocation per inserted item. Without that, your `LProbMap` and Java's `HashMap` differ only by where the next object pointer is read - a list in `LProbMap`, or the entry object in `HashMap`. Both are already in cache, so I would expect very similar performance, or worse because it has to iterate over more objects.

[Here](https://gist.github.com/dzaima/be4ef7efeda45a2930b1fb093f871c43) is a version of `LProbMap` utilizing a struct-of-arrays approach. It does mean that you have to read from three separate arrays, which would all be in different locations, but it's the best Java can currently offer.

**Comment by nomemory** [comment]
@dzaima I've just run some minimal benchmarks, and it seems your solution is making a difference and works better than LProbMap. When I will have time, I will redo the complete benchmarks, and chances are this might beat HashMap, at least for some. I will keep you updated.

**Comment by nomemory** [comment]
@dzaima Finished the benchmarks. And updated the article: https://www.andreinc.net/2021/11/08/a-tale-of-java-hash-tables

Thank you for the contribution. 

Your version works better than `LProbMap<K,V>` and even `HashMap<K,V>` for sizes < `1_000_000`. Its amazing what a simple change can do.

How did you knew about this trick ?

**Comment by dzaima** [comment]
It's an optimization strategy, common around SIMD, but useful in Java too, due to it being the only way to avoid allocations for an array of structures: https://en.wikipedia.org/wiki/AoS_and_SoA

Ideally the fields of a given entry would all be in order in one big array - `[key, value, hash, key, value, hash, key, value, hash]`. That layout is what you'd get in C/C++/Rust/etc, where you can have complex types that aren't heap-allocated, but currently (if ignoring preview/future features) there's no way to achieve that in Java.

**Comment by nomemory** [comment]
@dzaima Not even with Unsafe ?

**Comment by dzaima** [comment]
What you'd need is an array with mixed `Object` and `int` fields. `Unsafe` could _probably technically_ write them, but, at the very least, the garbage collector would _not_ be happy and crash.

[Primitive Objects](http://openjdk.java.net/jeps/401) should allow changing any of the entry types from from a `class` to a `primitive class`, but, as primitive types have no `null` value, you'd need to separate tombstones from empty entries (like my `LProbSOAMap` does with the hash value).
