### ISSUE TITLE
Tombstone count should be decreased

### ISSUE THREAD

**Issue by denisfalqueto** [nomemory/open-addressing-java-maps#2]
https://github.com/nomemory/open-addressing-java-maps/blob/2ab00568808c0d573b22ede75b02546bbd9fb9b7/src/main/java/net/andreinc/neatmaps/LProbMap.java#L126

The tombstone counter should be decreased when you use a bucket with a tombstone in it. You should update your blog post accordingly.

**Comment by nomemory** [comment]
Correct, thank you for spotting this.
